# Generated by Django 5.0 on 2024-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cat_img',
            field=models.ImageField(null=True, upload_to='category_imgs/'),
        ),
    ]
