# Generated by Django 5.0 on 2024-01-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_productcategory_cat_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='trans_ref',
            field=models.TextField(blank=True, null=True),
        ),
    ]
