# Generated by Django 4.2.9 on 2024-01-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name_plural': '5. Notifications'},
        ),
        migrations.AddField(
            model_name='notifications',
            name='notif_query',
            field=models.TextField(max_length=200, null=True, verbose_name='Notifications Query'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notif_subj',
            field=models.CharField(max_length=200, null=True, verbose_name='Notifications Subject'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notif_for',
            field=models.CharField(max_length=200, null=True, verbose_name='Notifications For'),
        ),
    ]
