# Generated by Django 4.2.9 on 2024-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_notification_delete_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(max_length=10, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('query', models.CharField(max_length=200, null=True)),
                ('countary', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField(max_length=6)),
                ('querydetail', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
